---
apiVersion: v1
kind: Service
metadata:
  name: vqa-app-service
  namespace: vqa-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 30080
  selector:
    app: vqa-app

