slide_info:
  g2e457098d7b_0_0:
    images:
      g2e4672f2781_0_13: '../insight-creator/ingress_perf_panels/panel_91_RPS edge.png'
      g2e4672f2781_0_14: '../insight-creator/ingress_perf_panels/panel_98_Average latency usage edge.png'
